// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: items.sql

package database

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const enchantItem = `-- name: EnchantItem :one
INSERT INTO items (
name,
effect,
damage,
item_type,
rental_fee,
maximum_uses,
remaining_uses ) VALUES (
$1, $2, $3, $4, $5, $6, $6
) RETURNING id, name, effect, damage, item_type, maximum_uses, remaining_uses
`

type EnchantItemParams struct {
	Name        string `json:"name"`
	Effect      string `json:"effect"`
	Damage      int16  `json:"damage"`
	ItemType    string `json:"item_type"`
	RentalFee   int32  `json:"rental_fee"`
	MaximumUses int16  `json:"maximum_uses"`
}

type EnchantItemRow struct {
	ID            uuid.UUID `json:"id"`
	Name          string    `json:"name"`
	Effect        string    `json:"effect"`
	Damage        int16     `json:"damage"`
	ItemType      string    `json:"item_type"`
	MaximumUses   int16     `json:"maximum_uses"`
	RemainingUses int16     `json:"remaining_uses"`
}

func (q *Queries) EnchantItem(ctx context.Context, arg EnchantItemParams) (EnchantItemRow, error) {
	row := q.db.QueryRow(ctx, enchantItem,
		arg.Name,
		arg.Effect,
		arg.Damage,
		arg.ItemType,
		arg.RentalFee,
		arg.MaximumUses,
	)
	var i EnchantItemRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Effect,
		&i.Damage,
		&i.ItemType,
		&i.MaximumUses,
		&i.RemainingUses,
	)
	return i, err
}

const rentItem = `-- name: RentItem :exec
INSERT INTO rentals (
item_id,
customer,
rental_fee) VALUES (
$1,
$2,
$3
)
`

type RentItemParams struct {
	ItemID    pgtype.UUID `json:"item_id"`
	Customer  string      `json:"customer"`
	RentalFee int32       `json:"rental_fee"`
}

func (q *Queries) RentItem(ctx context.Context, arg RentItemParams) error {
	_, err := q.db.Exec(ctx, rentItem, arg.ItemID, arg.Customer, arg.RentalFee)
	return err
}

const updateItemAStatus = `-- name: UpdateItemAStatus :exec
UPDATE items
SET loaned = $1, updated_at = CURRENT_TIMESTAMP
WHERE id = $2
`

type UpdateItemAStatusParams struct {
	Loaned pgtype.Bool `json:"loaned"`
	ID     uuid.UUID   `json:"id"`
}

func (q *Queries) UpdateItemAStatus(ctx context.Context, arg UpdateItemAStatusParams) error {
	_, err := q.db.Exec(ctx, updateItemAStatus, arg.Loaned, arg.ID)
	return err
}

const updateRentalStatus = `-- name: UpdateRentalStatus :exec
UPDATE rentals
SET returned_at = CURRENT_TIMESTAMP, status = 'returned'
WHERE id = $1
`

func (q *Queries) UpdateRentalStatus(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, updateRentalStatus, id)
	return err
}
