// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"database/sql/driver"
	"fmt"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type RentalStatus string

const (
	RentalStatusActive   RentalStatus = "active"
	RentalStatusReturned RentalStatus = "returned"
	RentalStatusOverdue  RentalStatus = "overdue"
)

func (e *RentalStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = RentalStatus(s)
	case string:
		*e = RentalStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for RentalStatus: %T", src)
	}
	return nil
}

type NullRentalStatus struct {
	RentalStatus RentalStatus `json:"rental_status"`
	Valid        bool         `json:"valid"` // Valid is true if RentalStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullRentalStatus) Scan(value interface{}) error {
	if value == nil {
		ns.RentalStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.RentalStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullRentalStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.RentalStatus), nil
}

type Item struct {
	ID            uuid.UUID          `json:"id"`
	Name          string             `json:"name"`
	Effect        string             `json:"effect"`
	Damage        int16              `json:"damage"`
	ItemType      string             `json:"item_type"`
	RentalFee     int32              `json:"rental_fee"`
	MaximumUses   int16              `json:"maximum_uses"`
	RemainingUses int16              `json:"remaining_uses"`
	Loaned        pgtype.Bool        `json:"loaned"`
	CreatedOn     pgtype.Timestamptz `json:"created_on"`
	UpdatedOn     pgtype.Timestamptz `json:"updated_on"`
}

type Rental struct {
	ID         uuid.UUID          `json:"id"`
	ItemID     pgtype.UUID        `json:"item_id"`
	Customer   string             `json:"customer"`
	RentalFee  int32              `json:"rental_fee"`
	Status     RentalStatus       `json:"status"`
	RentedAt   pgtype.Timestamptz `json:"rented_at"`
	DueAt      pgtype.Timestamptz `json:"due_at"`
	ReturnedAt pgtype.Timestamptz `json:"returned_at"`
}
